//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace techtalk_revised.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tevent_users
    {
        public int tevent_usersID { get; set; }
        public int userID { get; set; }
        public int eventID { get; set; }
    
        public virtual user user { get; set; }
        public virtual tevent tevent { get; set; }
    }
}
